version: '3'

services:

  db:
    image: postgres:11.5
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freetour
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 9000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ../backend
    image: backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/freetour
    ports:
      - 9001:8080
    restart: always
    depends_on:
      - db

  frontend:
    build: ../frontend
    image: frontend
    container_name: frontend
    ports:
      - 9002:80

volumes:
  pgdata:
